import { Product } from "./types";

/**
 * Mock catalog shaped to mirror the WooCommerce REST/Store API product
 * schema (id, slug, sku, price, stock_status, categories, meta_data for
 * purity/mass/batch). Swap `getProducts` / `getProductBySlug` for real
 * fetches against the WooCommerce API once the WordPress site is live —
 * see lib/woocommerce.ts.
 */
export const products: Product[] = [
  {
    id: "2",
    slug: "bpc-157-10mg",
    sku: "BPC-10",
    name: "BPC-157 10MG",
    category: "peptides",
    categoryLabel: "Peptide Research",
    image: "/images/products/vial-placeholder.png",
    price: 70,
    bulkOption: { qty: 10, price: 560, savePercent: 20 },
    purity: "98.51%",
    avgMass: "11.22 mg",
    rating: 4.8,
    reviewCount: 89,
    inStock: true,
    shortDescription: "Higher-concentration BPC-157 for extended research protocols.",
    description:
      "BPC-157 10mg, lyophilized and independently verified for identity and purity. Supplied for laboratory research use only.",
    storage: "Store lyophilized vials at 2–8°C. After reconstitution, use within 30 days and refrigerate.",
    reconstitution: "Reconstitute with bacteriostatic or sterile water appropriate for laboratory use.",
    badges: ["Save 20%"],
    batch: { code: "ALT-BPC10-08", date: "2026-08-09", status: "PASS" },
  },
  {
    id: "7",
    slug: "gp-3-10mg",
    sku: "GP3-10",
    name: "GP-3 10MG",
    category: "peptides",
    categoryLabel: "Peptide Research",
    image: "/images/products/vial-placeholder.png",
    price: 90,
    bulkOption: { qty: 10, price: 720, savePercent: 20 },
    purity: "99.69%",
    avgMass: "10.99 mg",
    rating: 4.7,
    reviewCount: 45,
    inStock: true,
    shortDescription: "Tri-agonist research peptide, standard concentration.",
    description:
      "GP-3 10mg vial for research protocols. 99.69% purity verified by independent third-party testing.",
    storage: "Store lyophilized vials at 2–8°C. After reconstitution, use within 30 days and refrigerate.",
    reconstitution: "Reconstitute with bacteriostatic or sterile water appropriate for laboratory use.",
    badges: ["Save 20%"],
    batch: { code: "ALT-GP3-10-07", date: "2026-07-30", status: "PASS" },
  },
  {
    id: "10",
    slug: "tesamorelin-10mg",
    sku: "TESA-10",
    name: "TESAMORELIN 10MG",
    category: "peptides",
    categoryLabel: "Peptide Research",
    image: "/images/products/vial-placeholder.png",
    price: 90,
    bulkOption: { qty: 10, price: 720, savePercent: 20 },
    purity: "99.86%",
    avgMass: "11.83 mg",
    rating: 4.6,
    reviewCount: 29,
    inStock: true,
    shortDescription: "GHRH-analog research peptide, standard concentration.",
    description:
      "Tesamorelin 10mg vial for research protocols. 99.86% purity verified by independent third-party testing.",
    storage: "Store lyophilized vials at 2–8°C. After reconstitution, use within 30 days and refrigerate.",
    reconstitution: "Reconstitute with bacteriostatic or sterile water appropriate for laboratory use.",
    badges: ["Save 20%"],
    batch: { code: "ALT-TESA10-07", date: "2026-07-18", status: "PASS" },
  },
  {
    id: "17",
    slug: "ghk-cu-50mg",
    sku: "GHK-50",
    name: "GHK-CU 50MG",
    category: "ancillaries",
    categoryLabel: "Peptide & Ancillary Research",
    image: "/images/products/vial-placeholder.png",
    price: 65,
    bulkOption: { qty: 10, price: 520, savePercent: 20 },
    purity: "99.4%",
    avgMass: "50.1 mg",
    rating: 4.7,
    reviewCount: 24,
    inStock: true,
    shortDescription: "Copper-peptide research compound, standard concentration.",
    description: "GHK-Cu 50mg vial for research protocols. 99.4% purity verified by independent third-party testing.",
    storage: "Store lyophilized vials at 2–8°C. After reconstitution, use within 30 days and refrigerate.",
    reconstitution: "Reconstitute with bacteriostatic or sterile water appropriate for laboratory use.",
    badges: ["Save 20%"],
    batch: { code: "ALT-GHK50-08", date: "2026-08-16", status: "PASS" },
  },
  {
    id: "18",
    slug: "mots-c-10mg",
    sku: "MOTS-10",
    name: "MOTS-C 10MG",
    category: "ancillaries",
    categoryLabel: "Peptide & Ancillary Research",
    image: "/images/products/vial-placeholder.png",
    price: 75,
    bulkOption: { qty: 10, price: 600, savePercent: 20 },
    purity: "99.5%",
    avgMass: "10.15 mg",
    rating: 4.8,
    reviewCount: 17,
    inStock: true,
    shortDescription: "Mitochondrial-derived peptide, standard concentration.",
    description: "MOTS-c 10mg vial for research protocols. 99.5% purity verified by independent third-party testing.",
    storage: "Store lyophilized vials at 2–8°C. After reconstitution, use within 30 days and refrigerate.",
    reconstitution: "Reconstitute with bacteriostatic or sterile water appropriate for laboratory use.",
    badges: ["Save 20%"],
    batch: { code: "ALT-MOTS10-08", date: "2026-08-17", status: "PASS" },
  },
  {
    id: "19",
    slug: "5-amino-1mq-50mg",
    sku: "5AM1MQ-50",
    name: "5-AMINO-1MQ 50MG",
    category: "ancillaries",
    categoryLabel: "Peptide & Ancillary Research",
    image: "/images/products/vial-placeholder.png",
    price: 70,
    bulkOption: { qty: 10, price: 560, savePercent: 20 },
    purity: "99.3%",
    avgMass: "50.2 mg",
    rating: 4.6,
    reviewCount: 14,
    inStock: true,
    shortDescription: "NNMT-inhibitor research compound, standard concentration.",
    description: "5-Amino-1MQ 50mg vial for research protocols. 99.3% purity verified by independent third-party testing.",
    storage: "Store lyophilized vials at 2–8°C. After reconstitution, use within 30 days and refrigerate.",
    reconstitution: "Reconstitute with bacteriostatic or sterile water appropriate for laboratory use.",
    badges: ["Save 20%"],
    batch: { code: "ALT-5AM1MQ-08", date: "2026-08-18", status: "PASS" },
  },
  {
    id: "21",
    slug: "thymosin-alpha-1-5mg",
    sku: "TA1-5",
    name: "THYMOSIN ALPHA-1 5MG",
    category: "peptides",
    categoryLabel: "Peptide Research",
    image: "/images/products/vial-placeholder.png",
    price: 60,
    bulkOption: { qty: 10, price: 480, savePercent: 20 },
    purity: "99.5%",
    avgMass: "5.06 mg",
    rating: 4.7,
    reviewCount: 21,
    inStock: true,
    shortDescription: "Immune-modulating research peptide, standard concentration.",
    description: "Thymosin Alpha-1 5mg vial for research protocols. 99.5% purity verified by independent third-party testing.",
    storage: "Store lyophilized vials at 2–8°C. After reconstitution, use within 30 days and refrigerate.",
    reconstitution: "Reconstitute with bacteriostatic or sterile water appropriate for laboratory use.",
    badges: ["Save 20%"],
    batch: { code: "ALT-TA15-08", date: "2026-08-19", status: "PASS" },
  },
  {
    id: "22",
    slug: "wolverine-stack-20mg",
    sku: "WOLV-20",
    name: "WOLVERINE STACK 20MG",
    category: "peptides",
    categoryLabel: "Peptide Research",
    image: "/images/products/vial-placeholder.png",
    price: 95,
    bulkOption: { qty: 10, price: 760, savePercent: 20 },
    avgMass: "20.4 mg",
    rating: 4.8,
    reviewCount: 26,
    inStock: true,
    shortDescription: "Pre-combined recovery blend for research convenience.",
    description: "Wolverine Stack 20mg blend for research protocols, independently tested for identity and mass.",
    storage: "Store lyophilized vials at 2–8°C. After reconstitution, use within 30 days and refrigerate.",
    reconstitution: "Reconstitute with bacteriostatic or sterile water appropriate for laboratory use.",
    badges: ["Save 20%"],
    batch: { code: "ALT-WOLV20-08", date: "2026-08-20", status: "PASS" },
  },
  {
    id: "23",
    slug: "glow-70mg",
    sku: "GLOW-70",
    name: "GLOW 70MG",
    category: "peptides",
    categoryLabel: "Peptide Research",
    image: "/images/products/vial-placeholder.png",
    price: 110,
    bulkOption: { qty: 10, price: 880, savePercent: 20 },
    avgMass: "70.3 mg",
    rating: 4.7,
    reviewCount: 19,
    inStock: true,
    shortDescription: "Pre-combined cellular-support blend for research convenience.",
    description: "GLOW 70mg blend for research protocols, independently tested for identity and mass.",
    storage: "Store lyophilized vials at 2–8°C. After reconstitution, use within 30 days and refrigerate.",
    reconstitution: "Reconstitute with bacteriostatic or sterile water appropriate for laboratory use.",
    badges: ["Save 20%"],
    batch: { code: "ALT-GLOW70-08", date: "2026-08-20", status: "PASS" },
  },
  {
    id: "24",
    slug: "sermorelin-10mg",
    sku: "SERM-10",
    name: "SERMORELIN 10MG",
    category: "peptides",
    categoryLabel: "Peptide Research",
    image: "/images/products/vial-placeholder.png",
    price: 65,
    bulkOption: { qty: 10, price: 520, savePercent: 20 },
    purity: "99.4%",
    avgMass: "10.11 mg",
    rating: 4.6,
    reviewCount: 12,
    inStock: true,
    shortDescription: "GHRH-analog research peptide, standard concentration.",
    description: "Sermorelin 10mg vial for research protocols. 99.4% purity verified by independent third-party testing.",
    storage: "Store lyophilized vials at 2–8°C. After reconstitution, use within 30 days and refrigerate.",
    reconstitution: "Reconstitute with bacteriostatic or sterile water appropriate for laboratory use.",
    badges: ["Save 20%"],
    batch: { code: "ALT-SERM10-08", date: "2026-08-21", status: "PASS" },
  },
  {
    id: "25",
    slug: "klow-80mg",
    sku: "KLOW-80",
    name: "KLOW 80MG",
    category: "peptides",
    categoryLabel: "Peptide Research",
    image: "/images/products/vial-placeholder.png",
    price: 125,
    bulkOption: { qty: 10, price: 1000, savePercent: 20 },
    avgMass: "80.2 mg",
    rating: 4.8,
    reviewCount: 15,
    inStock: true,
    shortDescription: "Pre-combined cellular-support blend for research convenience.",
    description: "KLOW 80mg blend for research protocols, independently tested for identity and mass.",
    storage: "Store lyophilized vials at 2–8°C. After reconstitution, use within 30 days and refrigerate.",
    reconstitution: "Reconstitute with bacteriostatic or sterile water appropriate for laboratory use.",
    badges: ["Save 20%"],
    batch: { code: "ALT-KLOW80-08", date: "2026-08-21", status: "PASS" },
  },
  {
    id: "26",
    slug: "selank-10mg",
    sku: "SEL-10",
    name: "SELANK 10MG",
    category: "peptides",
    categoryLabel: "Peptide Research",
    image: "/images/products/vial-placeholder.png",
    price: 60,
    bulkOption: { qty: 10, price: 480, savePercent: 20 },
    purity: "99.4%",
    avgMass: "10.08 mg",
    rating: 4.7,
    reviewCount: 18,
    inStock: true,
    shortDescription: "Anxiolytic peptide research compound, standard concentration.",
    description: "Selank 10mg vial for research protocols. 99.4% purity verified by independent third-party testing.",
    storage: "Store lyophilized vials at 2–8°C. After reconstitution, use within 30 days and refrigerate.",
    reconstitution: "Reconstitute with bacteriostatic or sterile water appropriate for laboratory use.",
    badges: ["Save 20%"],
    batch: { code: "ALT-SEL10-08", date: "2026-08-22", status: "PASS" },
  },
  {
    id: "27",
    slug: "cjc-1295-no-dac-5mg",
    sku: "CJC-5",
    name: "CJC-1295 WITHOUT DAC 5MG",
    category: "peptides",
    categoryLabel: "Peptide Research",
    image: "/images/products/vial-placeholder.png",
    price: 70,
    bulkOption: { qty: 10, price: 560, savePercent: 20 },
    purity: "99.6%",
    avgMass: "5.03 mg",
    rating: 4.8,
    reviewCount: 23,
    inStock: true,
    shortDescription: "GHRH-analog research peptide, standard concentration.",
    description: "CJC-1295 without DAC 5mg vial for research protocols. 99.6% purity verified by independent third-party testing.",
    storage: "Store lyophilized vials at 2–8°C. After reconstitution, use within 30 days and refrigerate.",
    reconstitution: "Reconstitute with bacteriostatic or sterile water appropriate for laboratory use.",
    badges: ["Save 20%"],
    batch: { code: "ALT-CJC5-08", date: "2026-08-22", status: "PASS" },
  },
];

export function getProducts() {
  return products;
}

export function getFeaturedProducts() {
  return products.filter((p) => ["bpc-157-10mg", "gp-3-10mg", "ghk-cu-50mg", "mots-c-10mg"].includes(p.slug));
}

export function getProductBySlug(slug: string) {
  return products.find((p) => p.slug === slug);
}

export function getRelatedProducts(slug: string, limit = 4) {
  const current = getProductBySlug(slug);
  if (!current) return [];
  return products.filter((p) => p.slug !== slug && p.category === current.category).slice(0, limit);
}

export const categories: { value: Product["category"] | "all"; label: string }[] = [
  { value: "all", label: "All Research" },
  { value: "peptides", label: "Peptide Research" },
  { value: "ancillaries", label: "Ancillary Research" },
];
